Algoritmo "senha_fixa"
// Disciplina   : [Lógica de Programação]
// Descrição   : Repetir a leitura de senha até que ela seja válida
// Autor(a)    : Rodrigo Regis
// Data atual  : 13-07-2021
Var

  senha: inteiro

Inicio
  escreval("Digite a senha")
  leia(senha)
  
  enquanto senha <> 2002 faca
     escreval("Tentativa Invalida! Tente Novamente")
     leia(senha)
  fimenquanto

  escreva("Acesso Permitido")
Fimalgoritmo