Algoritmo "Circulo"
// Disciplina   : Lógica de Programação
// Curso        : Udemy
// Descrição   : Fazer um programa para ler o valor "r" do raio de um círculo.
// Autor(a)    : Rodrigo Regggis
// Data atual  : 14-07-2021
Var

    raio, pii, area: real

Inicio

   escreval("Digite o raio")
   leia(raio)
   
   pii <- 3.14159
   
   area <- PI * (raio * raio)
   
   escreva("AREA = ", area:2:3)

Fimalgoritmo