Algoritmo "semnome"
// Disciplina  : Lógica de Programação]
// Curso       : Udemy
// Descrição   : Ler dois números inteiros e mostrar a soma.
// Autor(a)    : Rodrigo Regis
// Data atual  : 14-07-2021
Var

   num1, num2, total : inteiro

Inicio

    escreval("Digite o primeiro numero")
    leia(num1)
    
    escreval("Digite o segundo numero")
    leia(num2)
    
    total <- num1 + num2
    
    escreva("SOMA = ", total)

Fimalgoritmo